2006-Scape/2006Scape

- 2006Redone Server/src/redone/game/content/skills/fletching/LogCutting.java
checks if log is in inventory before fletching
> bandaid fix fletching

- 2006Redone Server/src/redone/game/npcs/Npc.java
I missed a line resulting in a one time sheep shear fiasco! My bad!
> Fixed an issue with sheep regrowth

- 2006Redone Server/src/redone/game/content/skills/core/Mining.java
- 2006Redone Server/src/redone/game/objects/ObjectsActions.java
essence should always give 5xp each
> Updated essence xp

- 2006Redone Server/src/redone/game/content/randomevents/RandomEventHandler.java
- 2006Redone Server/src/redone/game/content/skills/core/Fishing.java
- 2006Redone Server/src/redone/game/content/skills/core/Prayer.java
- 2006Redone Server/src/redone/game/content/skills/core/Woodcutting.java
- 2006Redone Server/src/redone/game/players/Player.java
- 2006Redone Server/src/redone/game/players/PlayerSave.java
- 2006Redone Server/src/redone/net/packets/impl/Commands.java
Update `randomToggle` to be `randomEventsEnabled` for less ambiguity.
Fix prayer and fishing random event enabled checks
> randomToggle -> randomEventsEnabled

- 2006Redone Server/src/redone/integrations/discord/JavaCord.java
- 2006Redone Server/src/redone/integrations/discord/commands/Commands.java
- 2006Redone Server/src/redone/integrations/discord/commands/Forum.java
- 2006Redone Server/src/redone/integrations/discord/commands/Hiscores.java
- 2006Redone Server/src/redone/integrations/discord/commands/Online.java
- 2006Redone Server/src/redone/integrations/discord/commands/Players.java
- 2006Redone Server/src/redone/integrations/discord/commands/Vote.java
- 2006Redone Server/src/redone/integrations/discord/commands/Website.java
Separated commands into own classes
added a few more simple af commands to make bot a bit more useful
> 2006ReBot Update

- 2006Redone Server/src/redone/integrations/discord/commands/Commands.java
> Show commands in a code block

- 2006Redone Server/src/redone/integrations/discord/commands/Players.java
Update message when no are players online:
_old_
`There is currently 0 player online.`
_new_
`There are currently 0 players online.`
> Update 0 players message

- 2006Redone Server/src/redone/Server.java
- 2006Redone Server/src/redone/integrations/discord/DiscordActivity.java
- 2006Redone Server/src/redone/integrations/discord/JavaCord.java
- 2006Redone Server/src/redone/integrations/discord/commands/Commands.java
- 2006Redone Server/src/redone/integrations/discord/commands/HeatMap.java
- 2006Redone Server/src/redone/integrations/discord/commands/Issues.java
Bot Activity Now Displays Current Players Online(Updated Every Minute? don't really understand game ticks xD)
Fixed ::commands Command
Added HeatMap & Issues Commands
> Discord Bot Update

- 2006Redone Server/src/redone/net/packets/impl/BankX2.java
Thanks to https://www.rune-server.ee/runescape-development/rs2-server/help/659176-2006redone-pi-bank-x-option-not-working-solved.html
> Fix Deposit & Withdraw "X" For Banking

- 2006Redone Server/src/redone/game/content/skills/core/Mining.java
- 2006Redone Server/src/redone/game/objects/ObjectsActions.java
> Allow player to mine Pure Essence

- 2006Redone Server/src/redone/game/content/skills/runecrafting/Runecrafting.java
This if function was unreachable beforehand, modified the code to use it.
`amount2 > 0 && amount > 0`
> Fix unreachable code block

- 2006Redone Server/src/redone/game/content/quests/QuestAssistant.java
> fixup sheep shearer/black knight

- 2006Redone Server/src/redone/game/content/combat/magic/MagicTeleports.java
- 2006Redone Server/src/redone/game/content/quests/QuestAssistant.java
- 2006Redone Server/src/redone/game/content/quests/QuestRewards.java
- 2006Redone Server/src/redone/game/content/quests/impl/BlackKnightsFortress.java
- 2006Redone Server/src/redone/game/dialogues/DialogueHandler.java
- 2006Redone Server/src/redone/game/players/PlayerSave.java
load player black knight progress.
save player black knight progress under the correct name.
give correct rewards - using the rewards function.
update max QP.
refactored quest rewards so they are more consistent.
> [Final?] Black knight fortress fixes

- 2006Redone Server/src/redone/game/content/skills/core/Mining.java
- 2006Redone Server/src/redone/game/objects/ObjectsActions.java
- 2006Redone Server/src/redone/net/packets/impl/ClickObject.java
- 2006Redone Server/src/redone/world/ObjectHandler.java
Refactored mining a little bit,
Can now mine all the rocks (blurite, gems, barbarian village rocks etc).
The respawn timers have been adjusted to the wiki.
The mining timer is the same as it was before. (time it takes to mine the ore)
closes #86
> Refactor mining, add all the rocks and ores

- 2006Redone Server/src/redone/game/players/Player.java
- 2006Redone Server/src/redone/net/packets/impl/Commands.java
- 2006Redone Server/src/redone/net/packets/impl/Walking.java
Refactored all the commands
Added `clicktotele` command for developers
> Refactor commands, Add click to tele command

- 2006Redone Server/data/cfg/item.cfg
- 2006Redone Server/data/cfg/npc.cfg
- 2006Redone Server/data/cfg/spawn-config.cfg
- 2006Redone Server/src/redone/game/content/quests/QuestAssistant.java
- 2006Redone Server/src/redone/game/content/quests/QuestRewards.java
- 2006Redone Server/src/redone/game/content/quests/impl/PiratesTreasure.java
- 2006Redone Server/src/redone/game/content/quests/impl/ShieldArrav.java
- 2006Redone Server/src/redone/game/content/quests/impl/VampyreSlayer.java
- 2006Redone Server/src/redone/game/dialogues/DialogueHandler.java
- 2006Redone Server/src/redone/game/npcs/NpcActions.java
- 2006Redone Server/src/redone/game/npcs/NpcHandler.java
- 2006Redone Server/src/redone/game/objects/ObjectsActions.java
- 2006Redone Server/src/redone/game/players/Client.java
- 2006Redone Server/src/redone/game/players/Player.java
- 2006Redone Server/src/redone/game/players/PlayerSave.java
- 2006Redone Server/src/redone/net/packets/impl/ClickingButtons.java
Add the Shield of Arrav quest _(only the Pheonix Gang part)_
May revisit in the future to add the other half.
Currently can be completed with 1 half of the shield.
Added a few spawns needed for the quests
Refactored the quest info for Vampyre Slayer too..
> Add Shield of Arrav

- 2006Redone Server/src/redone/game/shops/ShopAssistant.java
- round shop prices before multiplication
> Fix shop prices when selling multiple items

- 2006Redone Server/src/redone/game/npcs/NpcActions.java
- Fix Vampyre Slayer Quest
- Add 12 QP requirement to black knights fortress
closes #20
> Fix Vampyre Slayer Quest

- 2006Redone Client/src/Game.java
- 2006Redone Server/src/redone/game/players/Trading.java
- 2006Redone Server/src/redone/net/packets/impl/ClickingButtons.java
- 2006Redone Server/src/redone/net/packets/impl/ClickingStuff.java
Resolved issues around the trading system:
1. Can't trade anymore when other player isn't close;
2. Trade interface now close when other player disconnect or click the minimap;
3. Players cant no longer store items in the trade interface;
4. Items are properly distributed after any player closes the trade interface;
5. Added a message saying 'Trade completed.' after a trade is completed;
closes #59
> Trade issue

- 2006Redone Server/src/redone/game/dialogues/DialogueHandler.java
- 2006Redone Server/src/redone/game/players/Client.java
- 2006Redone Server/src/redone/game/players/PlayerAssistant.java
Made firstTimeTutorial handle the inital login stuff instead of it being ran with the dialogue
made the warning about the bank pin send for all players
fixed weight calculation on first login(closes #109)
> Read Comment

- .idea/artifacts/2006rebotted_jar.xml
- .idea/artifacts/localhost_2006rebotted_jar.xml
Makes them 1-2Mb again (instead of 40)
> Fix artifacts

- 2006Redone Server/src/redone/game/content/skills/crafting/CraftingData.java
> Fix Onyx Amulet Stringing

- 2006Redone Server/src/redone/game/content/combat/npcs/NpcAggressive.java
- 2006Redone Server/src/redone/game/npcs/NpcHandler.java
> Fixes npc aggressiveness

- 2006Redone Server/src/redone/net/packets/impl/AttackPlayer.java
Fixed an issue with teleother that wasnt working at all.
> Fixed an issue with teleother that wasnt working at all.

- 2006Redone Server/src/redone/game/content/combat/npcs/NpcAggressive.java
- 2006Redone Server/src/redone/game/npcs/NpcHandler.java
closes #160
Let me know if this doesn't work, but as far as I can tell it does. My local testing had it working perfectly.
> Finally should fix aggressiveness 

- 2006Redone Server/src/redone/game/players/Client.java
- 2006Redone Server/src/redone/game/shops/ShopAssistant.java
> Refactored stuff to facilitate resolving an issue regarding sellnig item to a full shop
> Removed double value message in shop
> Fixed stuff related to shop trading

- 2006Redone Server/data/logs/commands/andrew5.txt
- 2006Redone Server/data/logs/pking/killed/andrew5.txt
- 2006Redone Server/src/redone/Constants.java
- 2006Redone Server/src/redone/game/content/combat/CombatAssistant.java
- 2006Redone Server/src/redone/game/items/impl/RareProtection.java
- 2006Redone Server/src/redone/game/npcs/NpcHandler.java
- 2006Redone Server/src/redone/game/players/Player.java
- 2006Redone Server/src/redone/game/players/Trading.java
- 2006Redone Server/src/redone/game/shops/ShopAssistant.java
- 2006Redone Server/src/redone/net/packets/impl/ClickItem.java
- closes #205
- closes #197
- closes #145
Does the following
- Adds functional redemption prayer
- Fixes max stack deletion when trading
- Adds toggle for clue scrolls, currently set on disabled until someone gets the time to finish clue scrolls
- Cleans up a few minor things
- Removes a few bits of dead code
- Re enables rare detection
> Redemption Prayer/Fixes/Clues/Tidying up/Rares

- 2006Redone Server/src/com/rebotted/game/content/combat/range/DwarfCannon.java
Fixup being able to kill monsters without having correct slayer level
> Fixup being able to kill monsters without correct slayer level

- 2006Redone Server/src/com/rebotted/game/content/combat/range/DwarfCannon.java
- 2006Redone Server/src/com/rebotted/game/dialogues/DialogueHandler.java
- 2006Redone Server/src/com/rebotted/game/globalworldobjects/Doors.java
- 2006Redone Server/src/com/rebotted/game/globalworldobjects/DoubleDoors.java
- 2006Redone Server/src/com/rebotted/game/globalworldobjects/DoubleGates.java
- 2006Redone Server/src/com/rebotted/game/npcs/NPCDefinition.java
- 2006Redone Server/src/com/rebotted/game/npcs/NpcHandler.java
- 2006Redone Server/src/com/rebotted/game/players/PlayerAssistant.java
- 2006Redone Server/src/com/rebotted/net/packets/impl/Bank10.java
- 2006Redone Server/src/com/rebotted/net/packets/impl/ClickObject.java
- 2006Redone Server/src/com/rebotted/net/packets/impl/Commands.java
- Dwarf cannon can now be seen by anyone and not just the person who sets it down (they can also see the rotation now)
- Fixed doors being removed when clicking them
- Removed banking command for regular players
- Fixed nulodion now only gives if you have space
- Updated nulodion message so it doesnt say to find him at home
- Npcs wont follow you if you turn on the cantAttack comamand (for admins)
- Fixed gate at KBD
- Fixed the gates at Ice giants in wildy
closes #132
closes #203
closes #211
closes #6
also this one should be closed from previous patch
closes #219
> More fixes

- 2006Redone Server/src/com/rebotted/game/bots/BotHandler.java
- 2006Redone Server/src/com/rebotted/net/packets/impl/Commands.java
Closes #266 
Opening a shop now tells you the relevant shop commands, and running the shop commands tells you their relevant short-forms
> Small shop QoL

- 2006Redone Server/src/com/rebotted/GameEngine.java
- 2006Redone Server/src/com/rebotted/game/objects/impl/Climbing.java
- 2006Redone Server/src/com/rebotted/game/players/Player.java
- 2006Redone Server/src/com/rebotted/game/players/PlayerHandler.java
- 2006Redone Server/src/com/rebotted/net/packets/impl/Commands.java
- 2006Redone Server/src/com/rebotted/net/packets/impl/Walking.java
> Random fixes   2

- 2006Redone Server/src/com/rebotted/game/content/combat/CombatAssistant.java
- 2006Redone Server/src/com/rebotted/game/content/combat/npcs/NpcCombat.java
- 2006Redone Server/src/com/rebotted/game/content/combat/npcs/NpcEmotes.java
- 2006Redone Server/src/com/rebotted/game/npcs/NpcHandler.java
- 2006Redone Server/src/com/rebotted/game/players/Player.java
- Fixed npc drops/anims
- Fixed some combat sounds that were not working
- Made Kalphite Queen a multi area
> Quick patch

- 2006Redone Server/src/com/rebotted/game/items/ItemAssistant.java
- 2006Redone Server/src/com/rebotted/game/items/ItemDefinitions.java
- 2006Redone Server/src/com/rebotted/game/items/Weight.java
- 2006Redone Server/src/com/rebotted/game/players/Trading.java
- 2006Redone Server/src/com/rebotted/net/packets/impl/Walking.java
Some stuff on weight
closes #198
> Some stuff on weight

- 2006Redone Server/src/com/rebotted/game/items/ItemAssistant.java
- 2006Redone Server/src/com/rebotted/game/items/Weight.java
Brought back old code as what I previously did affected the time it takes to bank items.
> Fixed the delay on banking a non stackable item

- 2006Redone Server/data/logs/commands/andrew5.txt
- 2006Redone Server/data/logs/trades/recieved/andrew.txt
- 2006Redone Server/src/com/rebotted/game/content/combat/Specials.java
- 2006Redone Server/src/com/rebotted/game/content/skills/fletching/LogCutting.java
- 2006Redone Server/src/com/rebotted/game/content/skills/fletching/LogCuttingInterface.java
- 2006Redone Server/src/com/rebotted/game/items/Weight.java
- 2006Redone Server/src/com/rebotted/game/players/Player.java
- 2006Redone Server/src/com/rebotted/net/packets/impl/ClickObject.java
- Ranging guild now works
- Fletching should no longer randomly stop if more than on person is doing it
- Added dragon longsword special attack
Closes #346
Closes #216
Closes #245
> A few fun fixes

- 2006Redone Server/src/com/rebotted/game/content/skills/core/Woodcutting.java
- 2006Redone Server/src/com/rebotted/game/players/Player.java
- 2006Redone Server/src/com/rebotted/net/PacketSender.java
- 2006Redone Server/src/com/rebotted/net/packets/impl/Walking.java
- Shouldn't copy other players anim anymore if more than 1 person is woodcutting
closes #173
> Woodcutting animation fix

- 2006Redone Server/src/com/rebotted/GameEngine.java
Previous the main while{} loop featured a Thread.Sleep(600). This results in 600ms of unusable CPU time, or a maximum efficiency rate of 30%.
As each invocation is within a Runnable(), a synchronization lock is required to prevent concurrency.
> Moved main loop into FixedRate scheduler. Added sync lock on runnable.

- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/magic/Enchanting.java
first pr pls be gentle, pretty much just changed it to use the `hasRunes` and `deleteRunes` functions from the `CastRequirements` class and fixed a bug where the 3rd requirement wouldn't get removed.
> Fix for issue #364 - staffs are now supported when enchanting jewellery

- 2006Redone Server/data/logs/commands/andrew5.txt
- 2006Redone Server/src/main/java/com/rebotted/game/content/consumables/Food.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/music/sound/CombatSounds.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/skills/thieving/Pickpocket.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/skills/thieving/Stalls.java
- 2006Redone Server/src/main/java/com/rebotted/game/dialogues/DialogueHandler.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/Inventory.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/Item.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/ItemAssistant.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/ItemData.java
- 2006Redone Server/src/main/java/com/rebotted/game/npcs/drops/NPCDropsHandler.java
- 2006Redone Server/src/main/java/com/rebotted/game/objects/impl/OtherObjects.java
- 2006Redone Server/src/main/java/com/rebotted/game/objects/impl/Pickable.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/Player.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/BankAll.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ClickItem.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/InterfaceX.java
- 2006Redone Server/src/main/java/com/rebotted/world/Boundary.java
- 2006Redone Server/src/main/java/com/rebotted/world/ItemHandler.java
- Bank all should now work for all items again
- Fixed Al Kharid gate not functioning
- Added unique cabbage pickable for Falador
- Fixed desert disguise wrongly being noted
- Reformatted some of the food code
Closes #397
Closes #395
(I also included @Qweqker changes so that will fix Lumbridge bank boundary and adds his new cabbage effect)
> Some quick patches

- 2006Redone Server/src/main/java/com/rebotted/GameConstants.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/melee/MeleeData.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/npcs/NpcCombat.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/minigames/FightCaves.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/quests/impl/RestlessGhost.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/skills/SkillInterfaces.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/skills/cooking/Potatoes.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/skills/herblore/Herblore.java
- 2006Redone Server/src/main/java/com/rebotted/game/dialogues/DialogueHandler.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/ItemAssistant.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/UseItem.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/Weight.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/impl/Dye.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/impl/Flowers.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/impl/Greegree.java
- 2006Redone Server/src/main/java/com/rebotted/game/npcs/NpcHandler.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/Player.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerAssistant.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ItemOnGroundItem.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/Walking.java
- Nearly perfected fight caves now (should fix wave spawning, some dialogue bugs, instance issues fine now)
- Added fully working monkey gree grees
- Added ability to dye goblin mails
- Fixed somes skill interface typos
- Fixed restless ghost quest interface typo
- Clarified herb cleaning required level message
Closes #310 (the majority of stuff on there is fixed)
> Various thing

- 2006Redone Server/src/main/java/com/rebotted/GameConstants.java
- 2006Redone Server/src/main/java/com/rebotted/GameEngine.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/CombatAssistant.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/npcs/NpcCombat.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/skills/thieving/Pickpocket.java
- 2006Redone Server/src/main/java/com/rebotted/game/globalworldobjects/ClimbOther.java
- 2006Redone Server/src/main/java/com/rebotted/game/globalworldobjects/GateHandler.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/impl/Flowers.java
- 2006Redone Server/src/main/java/com/rebotted/game/objects/ObjectDefaults.java
- 2006Redone Server/src/main/java/com/rebotted/game/objects/Objects.java
- 2006Redone Server/src/main/java/com/rebotted/game/objects/impl/Levers.java
- 2006Redone Server/src/main/java/com/rebotted/game/objects/impl/OtherObjects.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/MainFrameIDs.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/Player.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerAction.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerAssistant.java
- 2006Redone Server/src/main/java/com/rebotted/util/MainFrameIDs.java
- 2006Redone Server/src/main/java/com/rebotted/world/clip/ObjectDefinition.java
- 2006Redone Server/src/main/java/com/rebotted/world/clip/Region.java
- Can't attack players or npcs through doors/walls anymore
- Cleaned up a few small bits of code
- Added a few new boundaries to the boundary system
- Removed dialogue asking are you sure you want to empty your inventory for admins
> A few things

- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/Specials.java
- 2006Redone Server/src/main/java/com/rebotted/game/content/skills/thieving/Pickpocket.java
- 2006Redone Server/src/main/java/com/rebotted/game/dialogues/DialogueHandler.java
- 2006Redone Server/src/main/java/com/rebotted/game/dialogues/DialogueOptions.java
- 2006Redone Server/src/main/java/com/rebotted/game/items/impl/EnchantStaff.java
- 2006Redone Server/src/main/java/com/rebotted/game/npcs/NpcActions.java
- 2006Redone Server/src/main/java/com/rebotted/game/objects/ObjectsActions.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerAssistant.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/BankX1.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ChallengePlayer.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ChangeAppearance.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ChangeRegions.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ClickNPC.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ClickObject.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ClickTab.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ClickingButtons.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ClickingInGame.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/FollowPlayer.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ItemClick2.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ItemClick2OnGroundItem.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ItemOnPlayer.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/MagicOnFloorItems.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/MoveItems.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/Report.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/SilentPacket.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/Trade.java
- 2006Redone Server/src/main/java/com/rebotted/world/Boundary.java
- 2006Redone Server/src/main/java/com/rebotted/world/clip/Region.java
- Fixed dragon battleaxe special
- Fixed banks in canifis and al kharid
- Added battlestaff enchanting
- Made fight caves entrance spawn at correct coords
- Did some small cleanup
> Few small changes

- 2006Redone Server/.gitignore
- 2006Redone Server/src/main/java/com/rebotted/GameEngine.java
- 2006Redone Server/src/main/java/com/rebotted/world/clip/Region.java
- 2006Redone Server/src/main/java/com/rebotted/world/clip/RegionFactory.java
Splits the loading of regions and population of clipping and object data in a factory class.
> Region factory 

- 2006Redone Server/src/main/java/com/rebotted/GameConstants.java
- 2006Redone Server/src/main/java/com/rebotted/game/bots/Bot.java
- 2006Redone Server/src/main/java/com/rebotted/game/bots/BotHandler.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerSave.java
- 2006Redone Server/src/main/java/com/rebotted/game/shops/ShopHandler.java
Players only keep their shops up if they're >50 total level and actually have something in them :)
> Non-spammy player shops

- 2006Redone Server/src/main/java/com/rebotted/game/bots/Bot.java
- 2006Redone Server/src/main/java/com/rebotted/game/objects/ObjectsActions.java
* Fixes passing through gate to King Lanthas' training ground
* Fixes ::shop not teleporting bot first try (thanks to SandroC for the code snippit)
> Some small fixes

- 2006Redone Server/src/main/java/com/rebotted/game/npcs/NpcHandler.java
- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ClickingButtons.java
Fixes #223 
Who ever wrote this code miss understood what `i` does.
> Npc aggression fix

- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ClickingButtons.java
Reverts 2006rebotted/2006rebotted#414
Was causing some weird issues that made you unable to run on any path unless you clicked "Run" while already moving
> Revert "[BUGFIX] Running in 1-tick"

- 2006Redone Client/src/main/java/Game.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/Player.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerAssistant.java
- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerSave.java
Fixed last logged in from IP
Various other changes/fixes
> Welcome Interface Fixup

- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerAssistant.java
Just plays a short song when a player levels up his skill.
> Song when player levels up a skill

- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/prayer/ActivatePrayers.java
- Adds Sound Effects for Protection Prayers
- Adds Sound Effect when Protection Prayers are disabled
> Sound Effects for Protection Prayers

- 2006Redone Server/src/main/java/com/rebotted/game/content/minigames/Barrows.java
- Spade now plays animation and sound.
> Spade Animation / SFX

- 2006Redone Server/src/main/java/com/rebotted/game/players/Player.java
Added an int to store the progression of Lost City (lostCity).
> Lost City Value for Quest Progression

- 2006Redone Server/data/cfg/spawns.json
Added NPCs Monk, Wizard, Archer and Warrior west of Lumbridge swamp for quest "Lost City".
> Added NPCs for Lost City Quest

- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerAssistant.java
When player levels up, makes the fireworks effect.
> Level Up Fireworks GFX

- 2006Redone Server/src/main/java/com/rebotted/game/content/quests/QuestAssistant.java
- Lost City progression can be opened
- Changed Max Quest Points
> Updated Lost City Progression and Max Quest Points

- 2006Redone Server/src/main/java/com/rebotted/game/players/Player.java
- An integer checks if leprechaun is spawned (Lost City)
> Added integer for leprechaunSpawned (lostCity)

- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ClickObject.java
- Leprechaun spawns at tree w/ sfx and quest conditions
- Tree Spirit spawns at tree w/ sfx and quest conditions
> Updated Actions for Spirit Tree and Leprechaun

- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerSave.java
- Added lostCity to playersave.java
> Lost City Progress Saves

- 2006Redone Server/src/main/java/com/rebotted/game/dialogues/DialogueOptions.java
- Added Dialogue Options for Warrior and Shamus
> Added Dialogue Options (lostCity)

- 2006Redone Server/src/main/java/com/rebotted/game/npcs/NpcActions.java
- Players can now properly interact with Monk, Archer, Wizard and Warrior
- Player can now interact with Shamus
> NPC Interaction (lostCity)

- 2006Redone Server/src/main/java/com/rebotted/net/packets/impl/Commands.java
- Admins can now turn into NPCs using the following commands "playnpc" or "pnpc".
> Added PNPC Command for Admins

- 2006Redone Server/src/main/java/com/rebotted/game/content/music/sound/CombatSounds.java
Fixed a glitch where the player would make a strange axe sound instead of the actual punch/kick sound.
> Fixed SFX for Unarmed Melee

- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/npcs/NpcCombat.java
Player makes sound when he takes damage
> Added SFX when player takes damage

- 2006Redone Server/src/main/java/com/rebotted/game/content/music/sound/CombatSounds.java
Added SFX for Guard attack and block
> Re: Guard SFX

- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/npcs/NpcEmotes.java
Guard NPC now has proper animations..
> Added Animations for Guard NPC

- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerAssistant.java
- Plays the death song when you respawn after dying
> Added Death Song

- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/melee/MeleeData.java
- Player now correctly blocks attacks when unarmed
- Player now has correct animations for all fight modes
> Fixed Player Unarmed Animations

- 2006Redone Server/src/main/java/com/rebotted/game/content/music/sound/CombatSounds.java
- Added all sounds for chickens
- Added proper sounds for sword and dagger
- Added some sounds for thief and farmer
- Fixed dds sound effect
> Combat Sound Fixes

- 2006Redone Server/src/main/java/com/rebotted/game/content/music/sound/CombatSounds.java
-Adds block sound and attack sound for wizards
> Added SFX for Dark Wizard

- 2006Redone Server/src/main/java/com/rebotted/game/players/PlayerAssistant.java
- Each skill has a corresponding level up song
- Some skills (Attack, Magic, Cooking) have multiple level up songs (Milestones like 99 or 10, 20, 30 etc.)
> Added Level Up Songs

- 2006Redone Server/src/main/java/com/rebotted/game/content/combat/npcs/NpcCombat.java
Dark Wizards now cast the correct spell
> Added GFX for Dark Wizard Spell

- 2006Redone Server/data/cfg/spawns.json
- Added Fishing Spots
- Added High Priest
- Added Monks
- Added Firebird of Entrana
- Added Chickens
> Added Npcs on Entrana

- 2006Redone Server/src/main/java/com/rebotted/game/dialogues/DialogueHandler.java
Added Dialogue for the following NPCs
- High Priest (Entrana)
- Warrior, Wizard, Monk and Archer (Lost City)
- Shamus (Lost City)
> Added Lost City Dialogues + Entrana Dialogues

- 2006Redone Server/src/main/java/com/rebotted/game/npcs/NpcActions.java
- Added Dialogue Action for High Priest (Entrana)
> Dialogue Action for High Priest

- 2006Redone Server/src/main/java/com/rebotted/game/dialogues/DialogueHandler.java
- 2006Redone Server/src/main/java/com/rebotted/game/npcs/NpcActions.java
- Added two different dialogues that can be triggered by talking to NPCS 1-6.
> Added Random Dialogue for Man and Woman NPCs

- .gitignore
- docker-compose.yml
Easily run a server in a docker container
> Add docker compose file for running servers in containers

- 2006Scape Client/src/main/java/Client.java
- 2006Scape Client/src/main/java/Game.java
- 2006Scape Client/src/main/java/Main.java
- 2006Scape Server/src/main/java/com/rs2/GameConstants.java
Added three possible arguments for launching client:
`server`, `username`, `password`.
- server:
- `-s`
- `-server`
- username:
- `-u`
- `-user`
- `-username`
- password:
- `-p`
- `-pass`
- `-password`
**_Testing on local:_**
```
java -jar client.jar -server localhost -u myusername -p mypassword
```
**NOTE:**
Also fixed up the server XP rate, must have changed it by accident in one of the other PRs 😅
> Process client arguments, Auto login option

- 2006Scape Server/src/main/java/com/rs2/game/content/combat/npcs/NpcCombat.java
Fixes #486 - The rock falling from the sky animation will now play
> Added jad ranged attack projectile

- 2006Scape Client/src/main/java/Main.java
- 2006Scape Server/ServerConfig.Sample.json
- 2006Scape Server/pom.xml
- 2006Scape Server/src/main/java/com/rs2/ConfigLoader.java
- 2006Scape Server/src/main/java/com/rs2/GameConstants.java
- 2006Scape Server/src/main/java/com/rs2/GameEngine.java
- 2006Scape Server/src/main/java/com/rs2/game/players/Player.java
- 2006Scape Server/src/main/java/com/rs2/game/players/PlayerSave.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/JavaCord.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/WelcomeMessage.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/commands/Commands.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/commands/Forum.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/commands/Issues.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/commands/Vote.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/commands/Website.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/commands/admin/AdminCommands.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/commands/admin/GameKick.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/commands/admin/Pin.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/commands/admin/Purge.java
- 2006Scape Server/src/main/java/com/rs2/net/packets/impl/Commands.java
> Various Changes

- 2006Scape Server/src/main/java/com/rs2/game/content/skills/thieving/SearchForTraps.java
- 2006Scape Server/src/main/java/com/rs2/game/content/skills/thieving/ThieveOther.java
- 2006Scape Server/src/main/java/com/rs2/game/items/ItemAssistant.java
- 2006Scape Server/src/main/java/com/rs2/game/npcs/NpcData.java
- 2006Scape Server/src/main/java/com/rs2/game/objects/ObjectsActions.java
- 2006Scape Server/src/main/java/com/rs2/game/objects/impl/Searching.java
- 2006Scape Server/src/main/java/com/rs2/game/players/Player.java
This is my first PR on this project, so any feedback is welcome :)
I've tested it locally and it works fine, it lets player to search for traps in chests, has cooldown with specific timers and rewards.
I've refactored some code in ThieveOther class (com.rs2.game.content.skills.thieving) and also addOrDropItem method in ItemAssistant class (com.rs2.game.items) to be able to drop item if player does not have stackable item and doesn't have space.
Let me know what you think :)
I guess it could close this [issue](https://github.com/2006-Scape/2006Scape/issues/221)
Thank you
> Implemented functionality where user can search for traps in some chests

- 2006Scape Client/src/main/java/ClientSettings.java
- 2006Scape Client/src/main/java/Main.java
- 2006Scape Client/src/main/java/RSApplet.java
* Changed JFrame Links to Variables in ClientSettings.java
* -qol/-fixes sets true BILINEAR_MINIMAP_FILTERING, FIX_TRANSPARENCY_OVERFLOW & FULL_512PX_VIEWPORT
* -no-nav/-disable-nav sets false SHOW_NAVBAR
> JFrame Links to Vars & Add Some Args

- 2006Scape Server/plugins/plugin/click/item/ItemFirstClick.kt
- 2006Scape Server/plugins/plugin/click/item/ItemOnItem.kt
- 2006Scape Server/plugins/plugin/click/item/ItemSecondClick.kt
- 2006Scape Server/plugins/plugin/click/item/ItemThirdClick.kt
- 2006Scape Server/plugins/plugin/click/npc/NpcFirstClick.kt
- 2006Scape Server/plugins/plugin/click/obj/ObjectFirstClick.kt
- 2006Scape Server/plugins/plugin/click/obj/ObjectSecondClick.kt
- 2006Scape Server/plugins/plugin/click/obj/ObjectThirdClick.kt
- 2006Scape Server/plugins/plugin/npc/fadli/SecondClick.kt
- 2006Scape Server/src/main/java/com/rs2/game/content/consumables/Food.java
- 2006Scape Server/src/main/java/com/rs2/game/content/skills/cooking/Cooking.java
- 2006Scape Server/src/main/java/com/rs2/game/content/skills/cooking/CookingTutorialIsland.java
- 2006Scape Server/src/main/java/com/rs2/game/content/skills/cooking/DairyChurn.java
- 2006Scape Server/src/main/java/com/rs2/game/content/skills/cooking/Potatoes.java
- 2006Scape Server/src/main/java/com/rs2/game/content/skills/core/Fishing.java
- 2006Scape Server/src/main/java/com/rs2/game/content/skills/core/Mining.java
- 2006Scape Server/src/main/java/com/rs2/game/items/impl/Dye.java
- 2006Scape Server/src/main/java/com/rs2/game/npcs/NpcActions.java
* Replaced a bunch of magic numbers with constants
* Fixed Spelling For Mackerel in Cooking & Food Classes
* Removed Some Dead IDs from the code(blurite in mining had Ids linked not in the cache for example)
> Replace a bunch of magic numbers & Fix Mackerel Spelling

- 2006Scape Server/src/main/java/com/rs2/game/content/traveling/Sailing.java
- 2006Scape Server/src/main/java/com/rs2/game/items/ItemAssistant.java
In this PR:
- Fixed Longsword combat style
- Fixed grammar related to sailing
> Various Fixes

- 2006Scape Server/src/main/java/com/rs2/game/content/combat/melee/MeleeData.java
> Block anim fixes

- 2006Scape Server/src/main/java/com/rs2/game/content/StaticItemList.java
- 2006Scape Server/src/main/java/com/rs2/game/content/StaticNpcList.java
- 2006Scape Server/src/main/java/com/rs2/game/content/StaticObjectList.java
> Suppress "unused" Warnings in StaticLists

- 2006Scape Server/src/main/java/com/rs2/game/items/DeprecatedItems.java
- 2006Scape Server/src/main/java/com/rs2/game/items/ItemData.java
- 2006Scape Server/src/main/java/org/apollo/cache/def/ItemDefinition.java
> Emergency Fix

- 2006Scape Server/src/main/java/com/rs2/game/shops/ShopAssistant.java
fixes https://github.com/2006-Scape/2006Scape/issues/602
> tokkul pricing

- 2006Scape Server/src/main/java/com/rs2/game/content/consumables/Food.java
- 2006Scape Server/src/main/java/com/rs2/util/ConstantReplacer.java
fixes constant replacer in intellij, this class will get phased out eventually
> Add exception fallback to support more java

- 2006Scape Server/src/main/java/com/rs2/game/content/combat/CombatAssistant.java
- 2006Scape Server/src/main/java/com/rs2/game/content/combat/npcs/NpcCombat.java
- 2006Scape Server/src/main/java/com/rs2/game/content/combat/range/DwarfCannon.java
- 2006Scape Server/src/main/java/com/rs2/game/content/skills/thieving/Pickpocket.java
- 2006Scape Server/src/main/java/com/rs2/game/npcs/Npc.java
- 2006Scape Server/src/main/java/com/rs2/game/npcs/NpcHandler.java
- 2006Scape Server/src/main/java/com/rs2/net/packets/impl/ClickNPC.java
> Fix Some NPC's Turning When Clicked That Shouldn't 

- 2006Scape Server/src/main/java/com/rs2/game/content/skills/firemaking/Firemaking.java
Proof for 60-119s: https://archive.is/zF5hb
(Fixes #546)
> Fixed fires to last 60-119 seconds

- 2006Scape Server/src/main/java/com/rs2/game/content/skills/firemaking/Firemaking.java
- 2006Scape Server/src/main/java/com/rs2/world/Boundary.java
> Fix Firemaking in Dwarven Areas

- 2006Scape Server/src/main/java/com/rs2/game/items/ItemAssistant.java
- 2006Scape Server/src/main/java/com/rs2/game/items/Weight.java
- 2006Scape Server/src/main/java/com/rs2/game/shops/ShopAssistant.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/JavaCord.java
- 2006Scape Server/src/main/java/com/rs2/integrations/discord/commands/Link.java
- 2006Scape Server/src/main/java/com/rs2/net/packets/impl/Commands.java
*[Fix Weight Calculation For Add/Remove Item In ItemAssistant](https://github.com/2006-Scape/2006Scape/commit/4547ef26388deb708eb9c0171a09814ceb4cb288)
*[Re-Add Simple Stuck Command That Logs To Discord To Prevent Abuse](https://github.com/2006-Scape/2006Scape/commit/394f3db44062b8c6766ee6e29c70032f66d12fa0)
*[Fix int/interface Command](https://github.com/2006-Scape/2006Scape/pull/633/commits/af95e760e704550c01a675b7002dd9ad1b378941)
*[Add World ID Check To DiscordBot Link Command](https://github.com/2006-Scape/2006Scape/pull/633/commits/791a1fb26562f09e892d68d1bb5f99c11b757332)
> Misc Changes

- 2006Scape Server/src/main/java/com/rs2/game/content/combat/CombatAssistant.java
- 2006Scape Server/src/main/java/com/rs2/game/players/PlayerAssistant.java
I'd actually also like to refactor this since followId vs followId2 is horrible naming, but, one step at a time... This is good to go as it stands right now.
> Fixed magic attacks running up to NPCs and Players

- 2006Scape Server/src/main/java/com/rs2/game/players/Player.java
- 2006Scape Server/src/main/java/com/rs2/net/packets/impl/Commands.java
With my custom print stream PR, this will also automatically log the player stuck command usage to a log file.
> Fixed stuck command and added home teleport command

- 2006Scape Server/src/main/java/com/rs2/GameEngine.java
- 2006Scape Server/src/main/java/com/rs2/net/packets/impl/Commands.java
- 2006Scape Server/src/main/java/com/rs2/util/Misc.java
This is a nice simple command plus there are some really helpful utility functions in here.
> Added uptime command and utility functions

- 2006Scape Server/ServerConfig.Sample.json
- 2006Scape Server/src/main/java/com/rs2/ConfigLoader.java
- 2006Scape Server/src/main/java/com/rs2/Constants.java
- 2006Scape Server/src/main/java/com/rs2/GameEngine.java
This is very cool, it includes performance metrics for cycle logging. It works great with the print stream PR too.
> Added cycle logging

- 2006Scape Client/src/main/java/Game.java
> Updated login server error message (typo fix)
