2006Redone Server/src/redone/integrations/discord/commands/Commands.java

Fixes the commands command,
Was originally missing a double quote mark,
Then an extra back-tick got added,
Then more back-ticks were added,
Then the fix keyword was removed,
I've added back the fix keyword which will give the commands the yellow coloring

fix the commands command finally

---

2006Redone Server/src/redone/integrations/discord/commands/Commands.java

commit by @RedSparr0w 
Fixes the commands command,
Was originally missing a double quote mark,
Then an extra back-tick got added,
Then more back-ticks were added,
Then the fix keyword was removed,
I've added back the fix keyword which will give the commands the yellow coloring

Finally "Fix" Discordbot ::commands

---

2006Redone Server/src/redone/game/content/quests/QuestRewards.java

should reward 3 QP _(currently only gives 1, says it gives 5)_
should reward 2500 coins _(currently says and give 5000)_
should not reward attack exp _(currently says and gives 10,000)_
should not award any items _(currently gives a sardine?)_
using wrong id for frame
[from the wiki](https://oldschool.runescape.wiki/w/Black_Knights%27_Fortress):

fix black knights quest rewards

---

2006Redone Server/src/com/rebotted/GameEngine.java
2006Redone Server/src/com/rebotted/game/players/PlayerHandler.java

Previously, you had to run `::update` and then I had to kill the server. This makes `::update` also turn `shutdownServer` to True, which kills the server.

Make ::update automatically restart server as well

---

2006Redone Server/src/com/rebotted/game/content/skills/core/Mining.java

"Multiple people mining rune essence gives the 'same' issue as thieving. player with highest mining level and/or lowest PID gets the essence, the other players do not. Mining resets for all players once a rock depletes, this should not be the case for rune essence"

Locally tested - fixed essence mining when multiple people are mining

---

2006Redone Server/src/main/java/com/rebotted/game/content/consumables/Food.java
2006Redone Server/src/main/java/com/rebotted/world/Boundary.java

- Added unique dialogue for cabbage that is supposed to spawn south of falador
- Added CABBAGE_SOUTH_OF_FALADOR in the foodtoeat enum
- Moved the unique food dialogue inside of the text if statements to prevent multiple statements of food.
I also adjusted the boundaries for the lumbridge bank or something idk.

Bank Adjustment, Cabbage Patch (Pun intended)

---

2006Redone Server/src/main/java/com/rebotted/net/packets/impl/ClickingButtons.java

Running will now start/stop when you press the buttons and not on the next walking packet
Related to issue #152

[BUGFIX] Running in 1-tick

---

2006Redone Client/src/main/java/Main.java

The URLs point to the same IP, but one of them will last longer. Easy

Update client IP

---

2006Redone Server/src/main/java/com/rebotted/game/content/skills/core/Mining.java
2006Redone Server/src/main/java/com/rebotted/net/packets/impl/Commands.java

**Mining**
- Fixed Mining Pickaxes: When using a mith pickaxe it showed it using addy and vise versa.
- Added Mining Sounds.
**Commands**
- Fixed Yell Command: It was originally using playerCommand.substring(5) which would return index out of bounds. (Changed to argument[0].

Mining Fixes | Yell Command Fix

---

2006Redone Server/src/main/java/com/rebotted/game/content/quests/QuestRewards.java

Lost City Reward gives the player 3 quest points and access to Zanaris.

Lost City Rewards Added

---

2006Redone Server/src/main/java/com/rebotted/game/objects/ObjectsActions.java

- Teleporting through Lumbridge Swamp Shed completes Lost City
- Reward is given (3QP + Access to Zanaris)

Added Quest Completion Condition for Lost City

---

2006Redone Server/src/main/java/com/rebotted/game/items/ItemAssistant.java

- Lost City completion is required to equip dragon longsword and dragon dagger

Lost City Required for Dragon Longsword / Dagger

---

2006Redone Server/data/cfg/spawns.json

- Druids now spawn all around Taverley
- Kaqemeex spawns at the Druidic Circle (Druidic Ritual Quest)
- Sanfew spawn near Herblore Shop (Druidic Ritual Quest)

Populated Taverley (Kaqemeex, Sanfew and Druids)

---

2006Redone Server/src/main/java/com/rebotted/game/content/skills/smithing/Smelting.java
2006Redone Server/src/main/java/com/rebotted/game/content/skills/smithing/SmithingData.java

If you make a trade request while smelting the game responds:
"You have received an unarmed"

Fixed wrong smelting response when trading & made full iron helm use 2 bars

---

2006Redone Server/src/main/java/com/rebotted/game/content/skills/firemaking/Firemaking.java

If you lit a fire too soon to your last fire you could light a fire and keep your log.
Also when this happens sometimes it would delete the log that you try to light and there is no fire.

Fixed firemaking log duplication

---

2006Redone Server/src/main/java/com/rebotted/game/npcs/NpcHandler.java

Potential aggression regression :)
#416 appears to have overzealously changed `NpcAggressive.isAggressive(i)` to `NpcAggressive.isAggressive(npcs[i].npcType)`.
This should not by needed because `i` within `NpcAggressive.isAggressive` is always passed into `NpcHandler.npcs[i]`
https://github.com/2006rebotted/2006rebotted/blob/12951be95407d172b91d06ff57e8376c8d71fb58/2006Redone%20Server/src/main/java/com/rebotted/game/content/combat/npcs/NpcAggressive.java#L22-L24
https://github.com/2006rebotted/2006rebotted/blob/12951be95407d172b91d06ff57e8376c8d71fb58/2006Redone%20Server/src/main/java/com/rebotted/game/content/minigames/FightCaves.java#L396-L397
As a sidenote, I noticed the issue within the Lumbridge cow field where some of the cows were aggresive on a local server current with master.
I …

Fix call to NpcAggressive.isAggressive

---

2006Redone Server/src/main/java/com/rebotted/game/content/skills/SkillHandler.java
2006Redone Server/src/main/java/com/rebotted/game/content/skills/smithing/Smelting.java

Smelting doesn't stop when you level up. As it continues smelting you lose ores but do not gain bars.
```
::tp 2973 3370
::skill 13 1
::empty
::item 436 10
::item 438 10
// smelt 10, get 10 bars
::empty
::item 436 10
::item 438 10
// smelt 10 again, it will level up, keep smelting, removing ore but not giving bars
```
Leveling up will clear `isSmelting` preventing bars for being given but not hitting a condition to break out of the smelting loop.
Utilize `resetSmelting` which, in addition to clearing `isSmelting` will cause it to end the smelting at one of these checks:
https://github.com/2006rebotted/2006rebotted/blob/fa167bacd3999efda6c7dff6d3d357cdb0731064/2006Redone%20Server/src/main/java/com/rebotted/game/content/skills/smithing/Smelting.java#L158-L165
Additionally, giving the item …

Fix bug where leveling up while Smelting would consume ores.

---

2006Redone Server/src/main/java/com/rebotted/game/content/skills/core/Mining.java

`giveGem` roll is not needed in `obtainGem` because it is already checked in order to call `giveGem`.
https://github.com/2006rebotted/2006rebotted/blob/15ab6253499e5f5a38372a296d35aa30492dd6d6/2006Redone%20Server/src/main/java/com/rebotted/game/content/skills/core/Mining.java#L232-L238
Calling random inside the Glory loop results in multiple rolls, potentially hiding the double `giveGem` check.

Fix gem check being rolled twice.

---

2006Scape Server/src/main/java/com/rs2/game/content/music/sound/CombatSounds.java

- Replace get NPC name associate array method to indexed array method
The current code uses a `GetNpcName` method which incorrectly assumes that the NPC List is an associate array where the ID is the index. This is not the case as the index is actually incremental.
While I would have rather changed the NPC List to be an associate array, as in the future writing code like this is not scalable for thousands of people on each server with thousands of NPC's, however that would require a rewrite of other methods too.
I found this issue when I attempted to kill Giant Mole which has an ID of 3340 but an array index of 2773. There is no npc with the index of 3340 so it crashed the server.

Fix Broken Game Sounds on Large ID NPCS

---

2006Scape Server/src/main/java/com/rs2/game/content/consumables/Food.java

- Adds all stew food items to the Food class
- Adds all gnomish food items(including the premade ones!) to the Food class
- Added Fruit Blast and Pineapple Punch (including premade versions) to the Food class (the rest boost stats like beers/pots so did not add)
- Added Rabbit, Ugthanki meat, Roast Bird meat, Thin Snail meat, Spider on stick, Spider on shaft, Roast Rabbit, Lean snail meat, Roast beast meat, Fat snail meat, Cooked slimy eel, Cooked chompy, Cooked fishcake, Rainbow fish, Cave eel, Cooked jubbly, Lava eel, Banana stew and Chocolatey milk to the Food class
- Chocolate bomb unique eat text
- "It heals some health." text added to default food items without unique eating text

Food Update: All stews, gnomish foods, and some misc foods/drinks

---

2006Scape Client/src/main/java/Game.java

Allow the client to launch if the File Server is down and we already have a cache downloaded.

Make file server optional if cache already downloaded

---

2006Scape Server/src/main/java/com/rs2/game/objects/impl/Climbing.java

East falador staircase was falling into the last if which was teleporting the player to a void. This fixes #452 however looking at the code the last catch block is probably causing issues else where.

East falador staircase to mine teleport bug

---

2006Scape Server/data/cfg/spawns.json
2006Scape Server/src/main/java/com/rs2/game/content/combat/npcs/NpcEmotes.java
2006Scape Server/src/main/java/com/rs2/game/content/skills/cooking/Cooking.java
2006Scape Server/src/main/java/com/rs2/game/npcs/NpcHandler.java
2006Scape Server/src/main/java/com/rs2/net/packets/impl/ClickObject.java

- Sea Turtle can be cooked, fixed xp received when cooking Manta Ray
- Al kharid warrior has correct emote when fighting
- Drop tables only roll once for items that do not have 100% drop rate (Prevents multiple items from rolling and dropping on same npc)
- Nerfed Tree Spirit (Lost City) max hit (From 20 to 10)
- Nerfed Abyssal Demon max hit (From 16 to 8)

Various Fixes

---

2006Scape Client/src/main/java/Game.java
2006Scape Client/src/main/java/RSApplet.java
2006Scape Client/src/main/java/RSFrame.java

The frame is no longer cut off at the top and other OSes (Linux) won't have extra padding around the edge.
Looks like this now:

Fixed client frame offsets/padding

---

2006Scape Client/src/main/java/ClientSettings.java
2006Scape Client/src/main/java/DrawingArea.java
2006Scape Client/src/main/java/Sprite.java
2006Scape Client/src/main/java/Texture.java

3 new options:
1) bilinear minimap filtering, smooths out jagged edges on the minimap and compass
2) transparency overflow fix, triangles could have lines drawn at their seams at most camera angles
3) full 512px viewport, the client has a "safe rendering size" that it used but resulted in 511px being drawn instead of 512, despite the area being 512. So you were left with a black border on the right side
Before vs After:

3 configurable graphics fixes in ClientSettings

---

2006Scape Server/data/cfg/shops.json

Quantities, orders, and shop names updated at:
- Al-Kharid
- Ape Atoll
- Ardougne
- Barbarian Village
- Burthrope
- Castle Wars
- Catherby
- Draynor Village
- Dwarven Mines
- Edgeville
- Entrana
- Falador
- Fishing Guild
- Fremennik Province
- Grand Tree
- Karamja
- Keldagrim
- Kharidian Desert
- Lletya
- Lumbridge
- Morytania
- Mos Le'Harmless
- Port Khazard
- Port Sarim
- Ranged Guild
- Taverly
- Tree Gnome Village
- Varrock
- Void Knight's Outpost
- Wilderness
- Yanille
- Zanaris
Also merged all duplicates that I could find. Some entries had the same ID.

Updated shops to have era accurate names, items, and quantities

---

2006Scape Server/src/main/java/com/rs2/game/content/combat/CombatAssistant.java
2006Scape Server/src/main/java/com/rs2/game/content/combat/Specials.java
2006Scape Server/src/main/java/com/rs2/game/content/combat/magic/MagicMaxHit.java
2006Scape Server/src/main/java/com/rs2/game/content/combat/magic/MagicSpells.java
2006Scape Server/src/main/java/com/rs2/game/content/combat/melee/MeleeData.java
2006Scape Server/src/main/java/com/rs2/game/content/combat/melee/MeleeMaxHit.java
2006Scape Server/src/main/java/com/rs2/game/content/combat/npcs/NpcCombat.java
2006Scape Server/src/main/java/com/rs2/game/content/combat/range/RangeMaxHit.java
2006Scape Server/src/main/java/com/rs2/game/content/consumables/Beverages.java
2006Scape Server/src/main/java/com/rs2/game/content/consumables/Food.java
2006Scape Server/src/main/java/com/rs2/game/content/consumables/Kebabs.java
2006Scape Server/src/main/java/com/rs2/game/content/consumables/Potions.java
2006Scape Server/src/main/java/com/rs2/game/content/minigames/castlewars/CastleWars.java
2006Scape Server/src/main/java/com/rs2/game/players/Player.java
2006Scape Server/src/main/java/com/rs2/game/players/PlayerAssistant.java
2006Scape Server/src/main/java/com/rs2/net/packets/impl/Commands.java

Fix for bug introduced with levelup in earlier PR. Only a single method is used for getting the level for XP. The method now also works more effectively. https://github.com/2006-Scape/2006Scape/commit/09068e31d34921fefe152b0aaab80e89f97bdaf3 is a summary of the changes to the methods

Fix getLevelforXP methods

---

2006Scape Server/src/main/java/com/rs2/Constants.java
2006Scape Server/src/main/java/com/rs2/game/content/minigames/Barrows.java
2006Scape Server/src/main/java/com/rs2/game/npcs/Npc.java
2006Scape Server/src/main/java/com/rs2/game/npcs/NpcHandler.java
2006Scape Server/src/main/java/com/rs2/game/players/Player.java
2006Scape Server/src/main/java/com/rs2/game/players/PlayerSave.java
2006Scape Server/src/main/java/com/rs2/net/packets/impl/Commands.java

This is a very cool system and allows for future expandability too, I have a couple of ideas building on this later on like an interface for boss NPC kills and an interface for slayer NPC kills.

Added NPC kill counts with message display

---

2006Scape Client/src/main/java/ClientSettings.java
2006Scape Client/src/main/java/Game.java
2006Scape Client/src/main/java/Main.java

This adds an option for automatic screenshots when clicking on the stats tab and opening the bank. This is basically a poor man's player exports. It's very handy, I love this feature and I think other players will love it too.
Also, there are official clients out there like RL that take automated screenshots on levelup, on kill and on death, etc so IMO this isn't too unheard of as a feature.

Added automatic screenshots

---

2006Scape Server/src/main/java/com/rs2/game/content/combat/CombatAssistant.java
2006Scape Server/src/main/java/com/rs2/game/content/combat/npcs/NpcCombat.java
2006Scape Server/src/main/java/com/rs2/game/content/combat/npcs/NpcEmotes.java
2006Scape Server/src/main/java/com/rs2/game/content/combat/range/DwarfCannon.java
2006Scape Server/src/main/java/com/rs2/game/content/minigames/magetrainingarena/Alchemy.java
2006Scape Server/src/main/java/com/rs2/game/content/skills/thieving/Stalls.java
2006Scape Server/src/main/java/com/rs2/game/npcs/NpcData.java
2006Scape Server/src/main/java/com/rs2/game/npcs/NpcHandler.java
2006Scape Server/src/main/java/com/rs2/game/players/Player.java
2006Scape Server/src/main/java/com/rs2/game/players/PlayerAssistant.java
2006Scape Server/src/main/java/com/rs2/net/packets/impl/AttackPlayer.java
2006Scape Server/src/main/java/com/rs2/net/packets/impl/ClickNPC.java
2006Scape Server/src/main/java/com/rs2/net/packets/impl/FollowPlayer.java
2006Scape Server/src/main/java/com/rs2/net/packets/impl/Walking.java

This one PR makes this code base so much more workable.
For example, I discovered that there was a bunch of GWD code in here, despite the fact that GWD wasn't added until 2007 not 2006.
Once this gets merged first I'll have to fix the merge conflicts in #658 after.

Refactoring follow player/NPC variables and NPC magic numbers

---

2006Scape Client/src/main/java/Game.java

This fixes drawing planes higher than 0 when hide roofs is enabled.
For example, when it's broken it looks like this on plane 1:
With this PR, it now looks like it's supposed to:

Fixed drawing plane higher than 0 with hide roofs enabled
